config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'signup'  => 'users#new'
  root 'homes#index'
  get 'admin' => 'admin/dashboards#index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'holiday' => 'holidays#index'
  namespace :admin do
    resources :dashboards
    resources :holidays
    resources :users
    get 'applied_leaves' => 'dashboard#applied_leaves'
    resources :emails
  end

  resources :users ,only: [:show, :new, :create, :edit, :update, :index] do
    resources :leaveemps
    get 'upcoming_leaves' => 'leaveemps#upcoming_leaves'
    get 'leave_history' => 'leaveemps#leave_history'
  end

  resources :roles
  resources :admin

  get 'users/add_manager'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
end

app/models/email.rb
class Email < ApplicationRecord
  validates :sender_email, presence: true
  validates :receiver_email, presence: true
  validates :subject, presence: true
  validates :body, presence: true

  enum status: { not_sent: 0, sent: 1 }
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/holiday.rb
class Holiday < ApplicationRecord
  #belongs_to :user
end

app/models/leaveemp.rb
class Leaveemp < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :startdate, presence: true
  validates :enddate, presence: true
  validate :validate_leave_schedule

  private
    # validates startdate should always lesser than enddate
    def validate_leave_schedule
      if startdate.present? & enddate.present?
        if self.enddate < self.startdate
          errors.add(:Leave, " start date and leave end date should be valid")
        end
      end
    end
end

app/models/manage.rb
class Manage < ApplicationRecord
belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 500 }
  validates :email, presence: true, length: { maximum: 255 },uniqueness: { case_sensitive: false }
  validates :password, presence: true,length: { minimum: 8 }
  validates :mobile, presence: true, length: { is: 10 } ,numericality: { message: "%{value} is not a mobile number" }

  has_one :user_role
  has_one :role, :through => :user_role, dependent: :destroy
  has_many :leaveemps, dependent: :destroy

  validates :mobile, presence: true,length: { minimum: 10 ,maximum: 10 }
  enum role: { employee: '1', admin: '2', trainee: '3', intern: '4' }
  # has_one :roles, dependent: :destroy
  has_many :manages, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :leaveemps, dependent: :destroy
  has_many :admin
  has_secure_password

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def admin?
    if role.to_s == Role.find_by(role: 'Admin').id
      return true
    else
      return false
    end
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  #admin_dashboard
  def index
    @users = User.all
  end

  def show
    @users = User.all
  end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  def index
    @holidays = Holiday.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :check_designation, except: [:index]
  def index
  end

  private
    def check_designation
      @designation = fetchDesignation
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]
  before_action :check_designation, only: [:show]

  def index
  end

  def show
    @user = User.find(params[:id])
    @path = request.headers["HTTP_REFERER"].to_s
    if current_user.id == @user.id
      @manages = Manage.all
      @managers = Manage.select("user_id")
      @manager_ids = @managers.map do |manager| manager.user_id end
      @employees = Assignment.select("user_id")
      @employee_ids = @employees.map do |employee| employee.user_id end
      if @manager_ids.include?(@user.id)
         @assign_ids = Assignment.where(mng_id:@user).map do |assigns| assigns.user_id end
         @users = User.all
      else
        if @employee_ids.include?(@user.id)
          @assigned_manager_id = 180#Assignment.find_by(user_id: @user).mng_id
          @manager_info = User.find(@assigned_manager_id)
        else
          @user
        end
      end
    else
      redirect_to user_path(current_user)
    end
  end

  def add_manager
    Assignment.create(user_id: params[:id], mng_id: params[:user][:manages])
    flash[:messge] = 'Manager Assigned Sucessfully'
    redirect_to admin_index_url
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
     redirect_to users_path
    else
      render 'new'
    end
    @user.role = Role.find_by(role: 'Employee')
    @user.save
  end

  def edit
    @user = User.find(params[:id])
    @manages = Manage.all
    @roles = Role.all
    @selected_user = @manages.map do |manage| manage.user_id end
    @assigns = Assignment.all.map do |assign| assign.user_id end
  end

  def update
    @user = User.find(params[:id])
    @path = request.headers["HTTP_REFERER"].to_s
    if params[:user][:manages] != nil
      Assignment.create(user_id: params[:id], mng_id: params[:user][:manages])
    end
    if @path.split("/").include?('edit')
      if @user.update(user_params)
        flash[:messge] = 'Updated Sucessfully'
        redirect_to user_path
      else
        flash[:messge] = 'Do Not Updated Sucessfully'
        render 'edit'
      end
    else
      redirect_to @path
    end
  end
  def destroy
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :mobile, :password, :password_confirmation)
    end

    def update_params
      params.require(:user).permit(:name, :email, :mobile)
    end

    def check_designation
      @designation = fetchDesignation
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # returns full page title
  def full_title(page_title = '')
    base_title = 'Employee Management Portal'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/leaveemps_helper.rb
module LeaveempsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id

    if user.admin?
      flash[:success] = 'Admin Log In Sucessfully'
      redirect_to user_path(user)
    else
      flash[:success] = 'Log In Sucessfully'
      redirect_to user
    end
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  #  def admin?
  #   if current_user.role.to_i == Role.find_by(role: 'Admin').id
  #     return true
  #   else
  #     return false
  #   end
  # end
end

app/views/admin/index.html.erb
<table border='1'>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Mobile Number</th>
    <th>Role</th>
    <th>Actions</th>
  </tr>
  <% @users.each do |u|%>
    <tr>
      <td><%= u.name   %></td>
      <td><%= u.email  %></td>
      <td><%= u.mobile %></td>
      <td><%= u.role %></td>
      <td><%= link_to 'Edit', edit_user_url(u) %></td>
    </tr>
  <% end %>
</table>

app/views/admin/show.html.erb
<table border='1'>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Mobile Number</th>
    <th>Actions</th>
  </tr>
  <% @users.each do |u|%>
    <tr>
      <td><%= u.name   %></td>
      <td><%= u.email  %></td>
      <td><%= u.mobile %></td>
      <td><%= @roles.find(@user_roles.find_by(user_id: u.id).role_id).ro
le%></td>
      <td><%= link_to 'Edit', edit_user_url(u) %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/_admin.html.erb
<header class='clearfix'>
  <div class="left-nav">
    <ul>
      <li><%= link_to "Users", admin_users_path %></li>
    </ul>
  </div>
  <div class="left-nav">
    <ul>
      <li><%= link_to "Holiday",admin_holidays_path %></li>
    </ul>
  </div>
</header>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
     <% if logged_in? %>
       <%= link_to "Employee Management Portal", user_path(current_user) %>
     <% else %>
       <%= link_to "Employee Management Portal", root_path, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav nav-tabs">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Home", user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Leaves", user_upcoming_leaves_path(current_user), class: 'nav-link' %>
          </li>

          <% if @designation == "Admin"%>
            <li class="nav-item">
              <%= link_to "Admin panel", admin_path, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "List of holidays", holiday_path, class: 'nav-link' %>
            </li>
          <% end %>
         <li class="nav-item">
            <%= link_to "Logout", logout_path, method: "delete", class: 'nav-link' %>
          </li>
    <% else %>
          <li class="nav-item">
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <%= link_to "Login", login_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin | Employee Management Portal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/admin/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <% message_type = message_type == 'notice' ? 'success' : message_type%>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/admin/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? %>
      <%= link_to "Employee Management Portal", user_path(current_user) %>
    <% else %>
      <%= link_to "Employee Management Portal", root_path, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav nav-tabs">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Dashboard", admin_index_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "List Of Holiday", admin_holidays_path, class: 'nav-link'%>
          </li>

          <li class="nav-item">
            <%= link_to "Applied Leaves", admin_applied_leaves_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to "Emails", admin_emails_path, class: 'nav-link'%>
          </li>

          <li class="nav-item">
            <%= link_to "Logout", logout_path, method: "delete", class: 'nav-link' %>
          </li>

        <% else %>
          <li class="nav-item">
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <%= link_to "Login", login_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>