config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'signup'  => 'users#new'
  root 'homes#index'
  get 'admin' => 'admin/dashboards#index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'holiday' => 'holidays#index'
  namespace :admin do
    resources :dashboards
    resources :holidays
    resources :users
    get 'applied_leaves' => 'dashboard#applied_leaves'
    resources :emails
  end

  resources :users ,only: [:show, :new, :create, :edit, :update, :index] do
    resources :leaveemps
    get 'upcoming_leaves' => 'leaveemps#upcoming_leaves'
    get 'leave_history' => 'leaveemps#leave_history'
  end

  resources :roles
  resources :admin

  get 'users/add_manager'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/models/holiday.rb
class Holiday < ApplicationRecord
  #belongs_to :user
end

app/controllers/admin/holidays_controller.rb
class Admin::HolidaysController < ApplicationController
  layout "admin"
  def index
    @holidays = Holiday.all
  end
  def show
    @holidays = Holiday.all
  end
  def new
    @holiday= Holiday.new
  end
  def create
    @holiday = Holiday.new(holiday_params)
    if @holiday.save
      redirect_to admin_holidays_path
    else
      render 'new'
    end
  end
  def destroy
    Holiday.find(params[:id]).destroy
    flash[:success] = 'Holiday Successfully deleted'
    redirect_to admin_holidays_path
  end
  def holiday_params
    params.require(:holiday).permit(:date, :reason)
  end
  def check_log_in
    if current_user.nil?
      redirect_to login_path
    end
  end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  def index
    @holidays = Holiday.all
  end
end

app/helpers/admin/holidays_helper.rb
module Admin::HolidaysHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/admin/holidays/index.html.erb
<table class="table table-hover">
  <tr>
    <th>Date</th>
    <th>Reason</th>
  </tr>
  <% @holidays.each do |h| %>
      <tr>
          <td><%= h.date %></td>
          <td><%= h.reason %></td>
          <td><%= link_to "Delete",admin_holiday_path(h), method: :delete %></li>
      </tr>
   <% end %>
</table>

<div class="left-nav">
    <ul>
      <li><%= link_to "Add",new_admin_holiday_path %></li>
    </ul>
</div>

app/views/admin/holidays/new.html.erb
<%=form_for(Holiday.new, url: admin_holidays_path ) do |f| %>

  <%= f.label :date %>
  <%= f.date_field :date, class: 'form-control' %>

  <%= f.label :reason %>
  <%= f.text_field :reason, class: 'form-control' %>
  <p>
    <%= f.submit ("Submit"), class: "btn btn-primary" %>
  </p>
<% end %>
<%= link_to 'Back', admin_holidays_path %>

app/views/admin/holidays/show.html.erb
<table border = 1>
  <th>
    <td>Date</td>
    <td>Reason</td>
  </th>
  <% @holidays.each_with_index do |h,index| %>
    <%if h.date.year == 2020 %>

      <tr>
          <td><%= index+1 %></td>
          <td><%= h.date %></td>
         <td><%= h.reason %></td>
      </tr>
    <% end %>
  <% end %>
</table>