config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'signup'  => 'users#new'
  root 'homes#index'
  get 'admin' => 'admin/dashboards#index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get 'holiday' => 'holidays#index'
  namespace :admin do
    resources :dashboards
    resources :holidays
    resources :users
    get 'applied_leaves' => 'dashboard#applied_leaves'
    resources :emails
  end

  resources :users ,only: [:show, :new, :create, :edit, :update, :index] do
    resources :leaveemps
    get 'upcoming_leaves' => 'leaveemps#upcoming_leaves'
    get 'leave_history' => 'leaveemps#leave_history'
  end

  resources :roles
  resources :admin

  get 'users/add_manager'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 500 }
  validates :email, presence: true, length: { maximum: 255 },uniqueness: { case_sensitive: false }
  validates :password, presence: true,length: { minimum: 8 }
  validates :mobile, presence: true, length: { is: 10 } ,numericality: { message: "%{value} is not a mobile number" }

  has_one :user_role
  has_one :role, :through => :user_role, dependent: :destroy
  has_many :leaveemps, dependent: :destroy

  validates :mobile, presence: true,length: { minimum: 10 ,maximum: 10 }
  enum role: { employee: '1', admin: '2', trainee: '3', intern: '4' }
  # has_one :roles, dependent: :destroy
  has_many :manages, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :leaveemps, dependent: :destroy
  has_many :admin
  has_secure_password

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def admin?
    if role.to_s == Role.find_by(role: 'Admin').id
      return true
    else
      return false
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user , only: [:show]
  layout "admin"
  def index
    @users = User.order(:id)
    @user_roles = UserRole.all
    @roles = Role.all
  end

  def show
    @user = User.find(params[:id])
    @user_roles = UserRole.all
    @roles = Role.all
    @manages = Manage.all
    @managers = Manage.select("user_id")
    @manager_ids = @managers.map do |manager| manager.user_id end
    @employees = Assignment.select("user_id")
    @employee_ids = @employees.map do |employee| employee.user_id end
    if @manager_ids.include?(@user.id)
       @assign_ids = Assignment.where(mng_id:@user).map do |assigns| assigns.user_id end
       @users = User.all
    else
      if @employee_ids.include?(@user.id)
        @assigned_manager_id = Assignment.find_by(user_id: @user).mng_id
        @manager_info = User.find(@assigned_manager_id)
      else
        @user
      end
    end
  end

  def add_manager
    Assignment.create(user_id: params[:id], mng_id: params[:user][:manages])
    flash[:messge] = 'Manager Assigned Sucessfully'
    redirect_to admin_index_url
  end

  def new
    @title = 'Sign Up'
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
     redirect_to users_path
    else
      render 'new'
    end

    @user.role = Role.find_by(role: 'Employee')
    @user.save
  end

  def edit
    @user_edit = User.find(params[:id])
    @manages = Manage.all
    @roles = Role.all
    @selected_user = @manages.map do |manage| manage.user_id end
    @assigns = Assignment.all.map do |assign| assign.user_id end
  end

  def update
    @user = User.find(params[:id])
    @path = request.headers["HTTP_REFERER"].to_s

    if params[:user][:manages] != nil
      Assignment.create(user_id: params[:id], mng_id: params[:user][:manages])
    end

    if @path.split("/").include?('edit')
      if @user.update(user_params)
        UserRole.where(user_id:params[:id]).update_all(role_id: params[:user][:role])
        flash[:notice] = 'Updated Sucessfully'
        redirect_to admin_users_path
      else
        flash[:notice] = 'Do Not Updated Sucessfully'
        render 'edit'
      end
    else
      redirect_to @path
    end
  end
  def destroy
  end

  private
   def user_params
      params.require(:user).permit(:name, :email, :mobile, :password, :password_confirmation)
   end

   def update_params
      params.require(:user).permit(:name, :email, :mobile)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]
  before_action :check_designation, only: [:show]

  def index
  end

  def show
    @user = User.find(params[:id])
    @path = request.headers["HTTP_REFERER"].to_s
    if current_user.id == @user.id
      @manages = Manage.all
      @managers = Manage.select("user_id")
      @manager_ids = @managers.map do |manager| manager.user_id end
      @employees = Assignment.select("user_id")
      @employee_ids = @employees.map do |employee| employee.user_id end
      if @manager_ids.include?(@user.id)
         @assign_ids = Assignment.where(mng_id:@user).map do |assigns| assigns.user_id end
         @users = User.all
      else
        if @employee_ids.include?(@user.id)
          @assigned_manager_id = 180#Assignment.find_by(user_id: @user).mng_id
          @manager_info = User.find(@assigned_manager_id)
        else
          @user
        end
      end
    else
      redirect_to user_path(current_user)
    end
  end

  def add_manager
    Assignment.create(user_id: params[:id], mng_id: params[:user][:manages])
    flash[:messge] = 'Manager Assigned Sucessfully'
    redirect_to admin_index_url
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
     redirect_to users_path
    else
      render 'new'
    end
    @user.role = Role.find_by(role: 'Employee')
    @user.save
  end

  def edit
    @user = User.find(params[:id])
    @manages = Manage.all
    @roles = Role.all
    @selected_user = @manages.map do |manage| manage.user_id end
    @assigns = Assignment.all.map do |assign| assign.user_id end
  end

  def update
    @user = User.find(params[:id])
    @path = request.headers["HTTP_REFERER"].to_s
    if params[:user][:manages] != nil
      Assignment.create(user_id: params[:id], mng_id: params[:user][:manages])
    end
    if @path.split("/").include?('edit')
      if @user.update(user_params)
        flash[:messge] = 'Updated Sucessfully'
        redirect_to user_path
      else
        flash[:messge] = 'Do Not Updated Sucessfully'
        render 'edit'
      end
    else
      redirect_to @path
    end
  end
  def destroy
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :mobile, :password, :password_confirmation)
    end

    def update_params
      params.require(:user).permit(:name, :email, :mobile)
    end

    def check_designation
      @designation = fetchDesignation
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  #  def admin?
  #   if current_user.role.to_i == Role.find_by(role: 'Admin').id
  #     return true
  #   else
  #     return false
  #   end
  # end
end

app/views/admin/users/edit.html.erb
<%= form_for @user_edit, :url => {:controller => params[:controller], :action => "update", :id => @user_edit } do |form| %>
    <% if @user_edit.errors.any? %>
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this information from being saved:
      </h2>
      <ul>
        <% @user_edit.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <p>
      <%= form.label :Name %><br>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.label :Email %><br>
      <%= form.text_area :email %>
    </p>
    <p>
      <%= form.label :Phone_Number %><br>
      <%= form.text_area :mobile %>
    </p>
     <p>
      <%= form.label :password %><br>
      <%= form.password_field :password %>
    </p>

    <p>
      <%= form.label :password_confirmation %><br>
      <%= form.password_field :password_confirmation %>
    </p>


      <p>
          <%= form.select(:manages, @selected_user.map do |i|  [User.find_by(id: i).name,User.find_by(id: i).id] end ,  {prompt: 'Select Person'}) %>
      </p>
      <p>
        <%= form.select(:role, @roles.map do |i|  [Role.find_by(id: i).role,Role.find_by(id: i).id] end ,{prompt: 'Select Role'}) %>
      </p>
    <%= form.submit %>
  <% end %>

app/views/admin/users/index.html.erb
<table border='1'>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
    <th>Mobile Number</th>
    <th>Designation</th>
    <th>Actions</th>
  </tr>
  <% @users.each do |u|%>
    <tr>
      <td><%= u.id   %></td>
      <td><%= u.name   %></td>
      <td><%= u.email  %></td>
      <td><%= u.mobile %></td>
      <% if  @user_roles.find_by(user_id: u.id) %>
        <td><%= @roles.find(@user_roles.find_by(user_id: u.id).role_id).role%></td>
      <% else %>
        <td> Not Assigned </td>
      <% end %>
      <td><%= link_to 'Edit', edit_admin_user_url(u) %></td>
    </tr>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<% provide(:title, @title) %>

<%=form_for @user do |f| %>

  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Name</label>
      <%= f.text_field :name, class: "form-control" %>

    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Email</label>
       <%= f.email_field :email, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="inputAddress2">Mobile</label>
    <%= f.text_field :mobile, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="inputAddress">Password</label>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="inputAddress2">Confirm Password</label>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

<%= f.submit "Create My Account", class: "btn btn-primary" %>
<% end %>

app/views/admin/users/show.html.erb
<h3> Personal Information </h3>
<table border = '1'>
  <tr>
    <td>Name</td>
    <td><%= @user.name %></td>
  </tr>
  <tr>
   <td>Email</td>
   <td><%= @user.email %></td>
  </tr>
  <tr>
    <td>Mobile Number</td>
    <td><%= @user.mobile %></td>
  </tr>
  <tr>
    <td>Designation</td>
    <td></td>
  </tr>
</table>
<br>

<% if @manager_ids.include?(@user.id)%>
      <h3> Assigned Employees Information </h3>
      <table border = 1>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Mobile Number</th>
        </tr>
        <% @assign_ids.uniq!.each do |u|%>
        <tr>
          <td><%= @users.find(u).name   %></td>
          <td><%= @users.find(u).email  %></td>
          <td><%= @users.find(u).mobile %></td>
        </tr>
        <% end %>
      </table>
<% else %>
      <% if @employee_ids.include?(@user.id) %>
        <h3> Manager Information </h3>
        <table border = '1'>
          <tr>
            <td>Name</td>
            <td><%= @manager_info.name %></td>
          </tr>
          <tr>
             <td>Email</td>
             <td><%= @manager_info.email %></td>
          </tr>
          <tr>
            <td>Mobile Number</td>
            <td><%= @manager_info.mobile %></td>
          </tr>
        </table>
      <% else %>
          <h3> Please Add Manager's Name</h3>
          <p>
            <%= form_for @user do |form| %>
             <p>
              <%= form.select(:manages, @manager_ids.map do |i|  [User.find_by(id: i).name,User.find_by(id: i).id] end ,{prompt: 'Select Person'}) %>
             </p>
             <p>
             <%= form.submit "Enter"%>
             </p>
            <% end %>
          </p>
      <% end %>
<% end %>